package e2e

import (
	"fmt"
	"path/filepath"
	"testing"

	"github.com/ku5ic/claude-kit/go/internal/testutil"
)

// guardCommitPayload is a Bash payload carrying command, with cwd when set.
func guardCommitPayload(command, cwd string) map[string]any {
	p := map[string]any{"tool_input": map[string]any{"command": command}}
	if cwd != "" {
		p["cwd"] = cwd
	}
	return p
}

// guardCommitStubbed is a sandbox whose PATH resolves gitleaks to a stub
// that ignores its arguments and exits with code, decoupling the exit-code
// branches from real repo state.
func guardCommitStubbed(t *testing.T, code int) *Kit {
	k := New(t)
	stubs := t.TempDir()
	Stub(t, filepath.Join(stubs, "gitleaks"), fmt.Sprintf("exit %d\n", code))
	k.PrependPath(stubs)
	return k
}

// `kit hook guard-commit` wiring: the binary reads the payload and the
// transcript it names, blocks with exit 2, and prints an ask as one
// PreToolUse JSON object. The checks themselves are tested in process, in
// internal/bashguard.
func TestGuardCommit(t *testing.T) {
	t.Parallel()
	k := guardCommitStubbed(t, 0)
	r := k.Hook("guard-commit", guardCommitPayload(`git commit -m "Generated by Claude"`, ""))
	r.Want(t, 2)
	r.Has(t, "Blocked by guard-commit: AI signature in commit message")
	r = k.Hook("guard-commit", guardCommitPayload(`git commit -m "fix: add sums"`, ""))
	r.Want(t, 0)
	r.Has(t, `"hookEventName":"PreToolUse"`, `"permissionDecision":"ask"`)
	transcript := filepath.Join(t.TempDir(), "t.jsonl")
	testutil.AppendJSONL(t, transcript, testutil.UserPrompt("fix it"), testutil.AssistantText("Commit as `fix: add sums`?"), testutil.UserPrompt("go"))
	p := guardCommitPayload(`git commit -m "fix: add sums"`, "")
	p["transcript_path"] = transcript
	k.Hook("guard-commit", p).Empty(t)
}
