package e2e

import (
	"fmt"
	"path/filepath"
	"strings"
	"testing"
)

// guardCommitPayload is a Bash payload carrying command, with cwd when set.
func guardCommitPayload(command, cwd string) map[string]any {
	p := map[string]any{"tool_input": map[string]any{"command": command}}
	if cwd != "" {
		p["cwd"] = cwd
	}
	return p
}

// guardCommitStubbed is a sandbox whose PATH resolves gitleaks to a stub
// that ignores its arguments and exits with code, decoupling the exit-code
// branches from real repo state.
func guardCommitStubbed(t *testing.T, code int) *Kit {
	k := New(t)
	stubs := t.TempDir()
	Stub(t, filepath.Join(stubs, "gitleaks"), fmt.Sprintf("exit %d\n", code))
	k.PrependPath(stubs)
	return k
}

// prose is n consecutive prose lines.
func prose(n int) string { return strings.Repeat("a line of plain prose\n", n) }

// rules/workflow.md section 1: a commit's message is shown before it runs,
// so a commit whose subject no earlier turn showed gets a prompt.
func TestGuardCommitAsksForAnUnshownMessage(t *testing.T) {
	text := func(s string) string {
		return fmt.Sprintf(`{"type":"assistant","message":{"content":[{"type":"text","text":%q}]}}`, s)
	}
	prompt := func(s string) string { return fmt.Sprintf(`{"type":"user","message":{"content":%q}}`, s) }
	commit := func(k *Kit, transcript string) Result {
		p := guardCommitPayload(`git commit -m "fix: add sums"`, "")
		if transcript != "" {
			path := filepath.Join(t.TempDir(), "t.jsonl")
			Write(t, path, transcript+"\n")
			p["transcript_path"] = path
		}
		return k.Hook("guard-commit", p)
	}
	k := guardCommitStubbed(t, 0)
	for name, transcript := range map[string]string{
		"no transcript":           "",
		"never shown":             prompt("fix it and commit"),
		"shown only in this turn": prompt("fix it and commit") + "\n" + text("Committing `fix: add sums`."),
	} {
		r := commit(k, transcript)
		r.Want(t, 0)
		if !strings.Contains(r.Output, `"permissionDecision":"ask"`) {
			t.Errorf("%s: no ask; output:\n%s", name, r.Output)
		}
	}
	shown := prompt("fix it") + "\n" + text("Commit as `fix: add sums`?") + "\n" + prompt("go")
	commit(k, shown).Empty(t)
}

func TestGuardCommit(t *testing.T) {
	// Each test feeds a synthetic Bash payload (a git commit command) to the
	// hook and asserts the exit code: 0 = allow, 2 = block.
	for _, tc := range []struct {
		name, command string
		status        int
	}{
		// passthrough: hook only inspects git commit commands
		{"passthrough: ls", "ls -la", 0},
		{"passthrough: git status", "git status", 0},
		{"passthrough: git push", "git push origin main", 0},
		{"passthrough: a path starting with commit isn't a commit", "cat > docs/rules.md <<EOF\nNever add Co-Authored-By: Claude\nEOF\ngit add commitlint.config.js", 0},
		{"block: a commit ended by a separator is still a commit", "git commit;echo \"Co-Authored-By: Claude\"", 2},
		{"block: a commit with its output redirected is still a commit", "git commit>out.log -m \"x\n\nCo-Authored-By: Claude\"", 2},
		{"block: a commit split by a line continuation is still a commit", "git -C . \\\ncommit -m \"x\n\nCo-Authored-By: Claude\"", 2},
		{"passthrough: commit as a word in a later command isn't a commit", "git add x\ncat > notes.md <<EOF\nWe commit to Co-Authored-By: Claude docs\nEOF", 0},
		{"passthrough: make commit after git status isn't a git commit", "git status && make commit && echo \"Co-Authored-By: Claude\"", 0},
		// allow: normal commits
		{"allow: feat conventional commit", `git commit -m "feat: add foo"`, 0},
		{"allow: fix conventional commit", `git commit -m "fix: bar bug"`, 0},
		{"allow: chore with scope", `git commit -m "chore(claude): clean up settings"`, 0},
		{"allow: plain subject without prefix", `git commit -m "Update README with install steps"`, 0},
		{"allow: commit with single-quoted message", `git commit -m 'feat: add foo'`, 0},
		// block: AI signatures in body
		{"block: Co-Authored-By Claude", `git commit -m "feat: x" -m "Co-Authored-By: Claude <claude@anthropic.com>"`, 2},
		{"block: Generated by Claude", `git commit -m "Generated by Claude"`, 2},
		{"block: Generated with Claude", `git commit -m "Generated with Claude"`, 2},
		// block: AI-tell phrasing in subject
		{"block: certainly in subject after conventional prefix", `git commit -m "feat: certainly add foo"`, 2},
		{"block: here is in subject", `git commit -m "fix: here is the patch"`, 2},
		{"block: i have at start of subject", `git commit -m "I have refactored the loop"`, 2},
		{"block: let me at start of subject", `git commit -m "let me clean this up"`, 2},
		{"block: in this commit phrasing", `git commit -m "in this commit we add the API"`, 2},
		// wall of text: only the heredoc opened on the git commit line is the message
		{"block: wall of text in a -m heredoc", "git commit -m \"$(cat <<'EOF'\nfeat: x\n\n" + prose(5) + "EOF\n)\"", 2},
		{"block: wall of text in a -F - heredoc", "git commit -F - <<'EOF'\nfeat: x\n\n" + prose(5) + "EOF", 2},
		{"block: wall of text in a heredoc with another delimiter", "git commit -m \"$(cat <<'MSG'\nfeat: x\n\n" + prose(5) + "MSG\n)\"", 2},
		{"block: wall of text in a <<- heredoc closed by a tab-indented delimiter", "git commit -F - <<-MSG\n\tfeat: x\n\n" + prose(5) + "\tMSG", 2},
		{"allow: wall of text in a heredoc writing a file", "cat > notes.md <<'EOF'\n" + prose(20) + "EOF\ngit add -A && git commit -qm init", 0},
		// signatures and subjects: the commit's heredoc is its message, another heredoc writes a file
		// the whole command is scanned: a message can come from anywhere in it
		{"block: a signature in a heredoc writing a file, even an unrelated one", "cat > notes.md <<EOF\nGenerated with Claude\nEOF\ngit commit -m \"feat: ok\"", 2},
		{"block: a signature in a message file a heredoc writes for -F", "cat > /tmp/msg <<'EOF'\nfeat: x\n\nCo-Authored-By: Claude <c@a.com>\nEOF\ngit commit -F /tmp/msg", 2},
		{"block: a signature in a heredoc opened on a continuation line", "git commit \\\n  -F - <<'EOF'\nfeat: x\n\nCo-Authored-By: Claude <c@a.com>\nEOF", 2},
		{"block: a signature after a here-string", "v=$(tr a-z A-Z <<< hello)\ngit commit -m \"feat: x\n\nCo-Authored-By: Claude <c@a.com>\"", 2},
		{"block: a signature after an arithmetic shift", "n=$((1<<b))\ngit commit -m \"feat: x\n\nCo-Authored-By: Claude <c@a.com>\"", 2},
		{"block: a signature in an unterminated commit heredoc", "git commit -m \"$(cat <<EOF\nfeat: x\nGenerated with Claude\n)\"", 2},
		{"block: a signature in a -m variable set earlier in the command", "MSG=\"Generated with Claude\"\ngit commit -m \"$MSG\"", 2},
		{"block: AI-tell phrasing in a heredoc subject", "git -C . commit -m \"$(cat <<'EOF'\nlet me fix this\nEOF\n)\"", 2},
		{"block: AI-tell phrasing in a <<- heredoc subject with a spaced opener", "git commit -F - <<- \"MSG\"\n\there is the patch\n\tMSG", 2},
		{"allow: a quoted -m subject before a heredoc body", "git commit -m \"feat: x\" -m \"$(cat <<'EOF'\nlet me explain\nEOF\n)\"", 0},
	} {
		t.Run(tc.name, func(t *testing.T) {
			New(t).Hook("guard-commit", guardCommitPayload(tc.command, "")).Want(t, tc.status)
		})
	}

	// gitleaks staged-secret scan: exit-code branching (0 = clean, 1 = leak,
	// anything else = operational error, fails open).
	// Placement regression: the scan must run before the subject-parsing
	// early exit, so it fires even for commits whose -m message doesn't match
	// the quoted-message extraction regex (e.g. no surrounding quotes at all).
	// Entry guard regression: "git -C <dir> commit" must still be recognized
	// as a commit invocation. A prior version required "git" and "commit" to
	// be whitespace-adjacent, so the -C global flag broke the match and the
	// hook exited before the gitleaks scan ever ran.
	for _, tc := range []struct {
		name, command string
		code, status  int
		has           string
	}{
		{"allow: gitleaks exits 0 (clean scan)", `git commit -m "feat: add foo"`, 0, 0, ""},
		{"block: gitleaks exits 1 (leak found)", `git commit -m "feat: add foo"`, 1, 2, "gitleaks flagged a secret"},
		{"allow (fail open): gitleaks exits a non-0/1 operational error code", `git commit -m "feat: add foo"`, 2, 0, "gitleaks exited 2"},
		{"block: gitleaks leak is still caught with an unquoted -m message", "git commit -m foo", 1, 2, "gitleaks flagged a secret"},
		{"allow: unquoted -m message with a clean gitleaks scan still passes through", "git commit -m foo", 0, 0, ""},
		{"block: gitleaks leak is still caught with no -m at all (--allow-empty)", "git commit --allow-empty", 1, 2, ""},
		{"block: git -C <dir> commit is still caught by the entry guard (gitleaks leak)", "git -C " + t.TempDir() + " commit -m test", 1, 2, "gitleaks flagged a secret"},
		{"allow: plain git commit (no -C) is unaffected by the -C entry guard fix", "git commit -m test", 0, 0, ""},
	} {
		t.Run(tc.name, func(t *testing.T) {
			r := guardCommitStubbed(t, tc.code).Hook("guard-commit", guardCommitPayload(tc.command, ""))
			r.Want(t, tc.status)
			if tc.has != "" {
				r.Has(t, tc.has)
			}
		})
	}

	t.Run("allow: gitleaks not installed, scan is skipped silently", func(t *testing.T) {
		k := New(t)
		k.Setenv("PATH", t.TempDir())
		r := k.Hook("guard-commit", `{"tool_input":{"command":"git commit -m \"feat: add foo\""}}`)
		r.Want(t, 0)
		// No transcript shows the message, so it asks; nothing about gitleaks.
		if strings.Contains(r.Output, "gitleaks") {
			t.Errorf("gitleaks notice in output:\n%s", r.Output)
		}
	})

	t.Run("gitleaks is invoked against payload .cwd, not the hook's own cwd", func(t *testing.T) {
		k := New(t)
		stubs := t.TempDir()
		argsFile := filepath.Join(t.TempDir(), "gitleaks.args")
		Stub(t, filepath.Join(stubs, "gitleaks"), fmt.Sprintf("echo \"$@\" > %q\nexit 0\n", argsFile))
		k.PrependPath(stubs)
		fixture := filepath.Join(Physical(t, t.TempDir()), "fixture-repo")
		Mkdir(t, fixture)
		k.Hook("guard-commit", guardCommitPayload(`git commit -m "feat: add foo"`, fixture)).Want(t, 0)
		if args := Read(t, argsFile); !strings.Contains(args, fixture) {
			t.Errorf("gitleaks args %q lack %q", args, fixture)
		}
	})
}
